# Generated by Django 6.0.5 on 2026-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioexterno',
            name='auth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
