# Generated by Django 4.2.16 on 2026-05-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_proyecto', '0005_alter_acudiente_id_alter_administrador_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, max_length=50)),
                ('identidad_otro', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=100)),
                ('estrato', models.CharField(blank=True, max_length=10)),
                ('ocupacion', models.CharField(blank=True, max_length=150)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100)),
                ('institucion_educativa', models.CharField(blank=True, max_length=255)),
                ('zona_residencia', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('num_embarazos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_partos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_cesareas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_abortos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('usa_anticonceptivo', models.BooleanField(blank=True, null=True)),
                ('metodo_anticonceptivo', models.CharField(blank=True, max_length=100)),
                ('fecha_ultima_citologia', models.DateField(blank=True, null=True)),
                ('en_gestacion', models.BooleanField(blank=True, null=True)),
                ('en_lactancia', models.BooleanField(blank=True, null=True)),
                ('tiene_hijos', models.BooleanField(blank=True, null=True)),
                ('numero_hijos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edades_hijos', models.CharField(blank=True, max_length=255)),
                ('vive_solo', models.BooleanField(blank=True, null=True)),
                ('red_apoyo', models.TextField(blank=True)),
                ('dificultad_movilidad', models.BooleanField(blank=True, null=True)),
                ('caidas_ultimo_anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('polifarmacia', models.BooleanField(blank=True, null=True)),
                ('vida_sexual_activa', models.BooleanField(blank=True, null=True)),
                ('consume_alcohol', models.CharField(blank=True, max_length=50)),
                ('consume_tabaco', models.CharField(blank=True, max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizacion', to='nombre_proyecto.usuarioexterno')),
            ],
        ),
    ]
