# Generated by Django 4.2.16 on 2026-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_proyecto', '0006_caracterizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='metodo_proteccion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='num_parejas_actuales',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='num_parejas_ultimo_anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='prueba_ets',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
