# Generated by Django 4.2.16 on 2026-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_proyecto', '0007_caracterizacion_metodo_proteccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='citologia_rectal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='citologia_vaginal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='citologia_vph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='pareja_sexual_es',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='caracterizacion',
            name='tiene_pareja',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
